### ISSUE TITLE
Sanitize is not working properly in newlines are present.

### ISSUE THREAD

**Issue by charlestonsoftware** [jedluk/use-exportable-csv#1]
`const data = {
     field: 'some text\nmore text',
};

const csvLink = useExportableCSV(data);
`

This example does not encapsulate the field in quotes, which it should if there is a delimiter (,) or a newline (\n or \r or \r\n).  This causes the resulting CSV to incorrectly setup a new record at the newline versus storing the data in a single text field with an inline newline character.

`const data = {
     field: '\"some text\nmore text\"',
};

const csvLink = useExportableCSV(data);
`

This works, because it forces quote delimiters on a text field that contains a newline.   The record stays intact and renders in most spreadsheet apps with a single column with newline characters.

`const data = {
     field: 'some, text\nmore text',
};

const csvLink = useExportableCSV(data);
`

This example DOES encapsulate in quotes because the data has a comma.   This is correct.

`const data = {
     field: '\"some,text\nmore text\"',
};

const csvLink = useExportableCSV(data);
`

This breaks the standard CSV output.  The comma inside the forced quotes put in place to retain the newlines causes sanitize() to quote the already-quoted data.   This results in an errant newline being rendered and breaking the record to a new entry.

Possible fixes --

1. Update sanitize() to not only quote on delim (,) but quote if string includes delim(,) or newline characters.

2. Update sanitize to NOT quote if the data is wrapped in quotes already , regex match ^\".*?\"$  then do NOT quote.

**Comment by jedluk** [comment]
Hi there ! Thanks for raising this , I've prepared small fix for it which do the following:

1. Return original phrase if it is already quoted
2. Quote phrase if it contains delimiter or new line sign

```
function sanitize(delimeter: CSVDelimiter): (values: string[]) => string[] {
  return (values: string[]): string[] =>
    values.map((value) => {
      if (QUOTED_REGEX.test(value)) {
        return value
      }
      return value.includes(delimeter) || value.includes(NEW_LINE_SIGN)
        ? `"${value}"`
        : value
    })
}
```

Feel free to play around on branch _FIX-newline-in-phrase-breaks-csv-output_ . I'm planning to release version 1.0.1 on friday 

Adjacent [PR](https://github.com/jedluk/use-exportable-csv/pull/2)

**Comment by jedluk** [comment]
@charlestonsoftware
new version has been deployed, you can check it [here](https://codesandbox.io/s/jolly-morning-tpwww)
